import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Bell, CheckCircle2, CircleHelp, History, KeyRound, Mail, MessageCircle, ShieldAlert, Trash2, UserRound } from 'lucide-react';
import PageWrapper from '../components/layout/PageWrapper';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import { useApp } from '../context/AppContext';

function Shell({ title, eyebrow, children }) {
  return <PageWrapper><div className="py-6 lg:py-8 max-w-3xl mx-auto"><Link to="/profile" className="inline-flex items-center gap-2 text-sm no-underline mb-6" style={{color:'var(--text-secondary)'}}><ArrowLeft size={16}/> Back to profile</Link><p className="text-xs uppercase tracking-[.16em]" style={{color:'var(--accent)'}}>{eyebrow}</p><h1 className="text-3xl font-bold mt-2 mb-7" style={{fontFamily:'var(--font-display)'}}>{title}</h1>{children}</div></PageWrapper>;
}

function Toggle({ value, onChange, label }) {
  return <button aria-label={label} onClick={() => onChange(!value)} className="relative w-12 h-7 rounded-full transition-colors" style={{background:value?'var(--accent)':'var(--bg-tertiary)',border:'1px solid var(--border)'}}><span className="absolute top-0.5 w-5 h-5 rounded-full transition-all" style={{left:value?25:3,background:value?'#062119':'var(--text-tertiary)'}}/></button>;
}

export function AccountDetails() {
  const { user, setUser, addToast } = useApp(); const [name, setName] = useState(user?.name || ''); const [saving, setSaving] = useState(false);
  const save = async event => { event.preventDefault(); setSaving(true); const response=await fetch('/api/profile',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})}); const data=await response.json(); setSaving(false); if(!response.ok) return addToast({type:'error',message:data.detail||'Could not update your profile.'}); setUser(data.user); addToast({type:'success',message:'Account details saved.'}); };
  return <Shell eyebrow="Account" title="Account details"><Card hover={false}><form onSubmit={save} className="space-y-5"><div className="flex items-center gap-3"><span className="w-11 h-11 rounded-xl flex items-center justify-center" style={{background:'var(--accent-dim)',color:'var(--accent)'}}><UserRound size={20}/></span><div><p className="font-semibold">Your DJAGA profile</p><p className="text-xs" style={{color:'var(--text-tertiary)'}}>Used to personalise your protection hub.</p></div></div><label className="block text-sm font-medium">Display name<input value={name} onChange={event=>setName(event.target.value)} minLength="2" maxLength="80" required className="mt-2 w-full px-4 py-3 rounded-xl outline-none" style={{background:'var(--bg-tertiary)',border:'1px solid var(--border)',color:'var(--text-primary)'}}/></label><label className="block text-sm font-medium">Email address<input value={user?.email || ''} disabled className="mt-2 w-full px-4 py-3 rounded-xl outline-none opacity-70" style={{background:'var(--bg-tertiary)',border:'1px solid var(--border)',color:'var(--text-primary)'}}/></label><p className="text-xs" style={{color:'var(--text-tertiary)'}}>Your email is your sign-in identity and cannot be changed here.</p><Button type="submit" loading={saving}>Save changes</Button></form></Card></Shell>;
}

export function CommunicationPreferences() {
  const { addToast } = useApp(); const [settings,setSettings]=useState(null); const [saving,setSaving]=useState(false);
  useEffect(()=>{fetch('/api/profile/settings',{credentials:'include'}).then(r=>r.json()).then(setSettings);},[]);
  const save=async next=>{setSettings(next);setSaving(true);const response=await fetch('/api/profile/settings',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const data=await response.json();setSaving(false);if(!response.ok)return addToast({type:'error',message:data.detail||'Could not save preferences.'});setSettings(data);addToast({type:'success',message:'Communication preferences saved.'});};
  if(!settings)return <Shell eyebrow="Account" title="Communication preferences"><Card hover={false}>Loading preferences…</Card></Shell>;
  const rows=[['email_updates','Email security updates','Receive product and security updates by email',Mail],['scam_alerts','Emerging scam alerts','Be notified when local scam patterns increase',Bell]];
  return <Shell eyebrow="Account" title="Communication preferences"><Card padding={false} hover={false}>{rows.map(([key,title,detail,Icon])=><div key={key} className="flex items-center gap-3 px-5 py-5 border-b last:border-0" style={{borderColor:'var(--border)'}}><span className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background:'var(--accent-dim)',color:'var(--accent)'}}><Icon size={18}/></span><span className="flex-1"><span className="block text-sm font-semibold">{title}</span><span className="block text-xs mt-1" style={{color:'var(--text-tertiary)'}}>{detail}</span></span><Toggle label={title} value={settings[key]} onChange={value=>save({...settings,[key]:value})}/></div>)}</Card>{saving&&<p className="text-xs mt-3" style={{color:'var(--text-tertiary)'}}>Saving…</p>}</Shell>;
}

export function PasswordSecurity() {
  const { user, addToast }=useApp();const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [saving,setSaving]=useState(false);
  const save=async event=>{event.preventDefault();if(next!==confirm)return addToast({type:'error',message:'New passwords do not match.'});setSaving(true);const r=await fetch('/api/profile/password',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({current_password:current,new_password:next})});const data=await r.json();setSaving(false);if(!r.ok)return addToast({type:'error',message:data.detail||'Could not update password.'});setCurrent('');setNext('');setConfirm('');addToast({type:'success',message:'Password updated securely.'});};
  if(user?.auth_method==='mydigitalid_sim')return <Shell eyebrow="Account" title="Password & security"><Card hover={false}><p className="text-sm" style={{color:'var(--text-secondary)'}}>This demo identity is signed in through the simulated MyDigital ID flow. Password changes are not available for this account.</p></Card></Shell>;
  return <Shell eyebrow="Account" title="Password & security"><Card hover={false}><form onSubmit={save} className="space-y-4"><div className="flex items-center gap-3 mb-2"><KeyRound style={{color:'var(--accent)'}}/><p className="text-sm" style={{color:'var(--text-secondary)'}}>Use at least 8 characters. Your current password is required.</p></div>{[['Current password',current,setCurrent],['New password',next,setNext],['Confirm new password',confirm,setConfirm]].map(([label,value,setter])=><label key={label} className="block text-sm font-medium">{label}<input type="password" value={value} onChange={event=>setter(event.target.value)} minLength="8" required className="mt-2 w-full px-4 py-3 rounded-xl outline-none" style={{background:'var(--bg-tertiary)',border:'1px solid var(--border)',color:'var(--text-primary)'}}/></label>)}<Button type="submit" loading={saving}>Update password</Button></form></Card></Shell>;
}

export function DetectionPreferences() {
  const [health,setHealth]=useState(null);const { addToast }=useApp();const [privateAnalysis,setPrivateAnalysis]=useState(false);
  useEffect(()=>{fetch('/api/healthz').then(r=>r.json()).then(setHealth).catch(()=>setHealth({agents:{}}));fetch('/api/profile/settings',{credentials:'include'}).then(r=>r.json()).then(data=>setPrivateAnalysis(Boolean(data.private_analysis)));},[]);
  const toggle=async value=>{setPrivateAnalysis(value);await fetch('/api/profile/settings',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({private_analysis:value})});addToast({type:'success',message:value?'Private analysis enabled.':'Private analysis disabled.'});};
  return <Shell eyebrow="Protection" title="Detection preferences"><Card hover={false}><div className="flex items-center justify-between gap-4 pb-5 border-b" style={{borderColor:'var(--border)'}}><div><p className="font-semibold">Private analysis</p><p className="text-xs mt-1" style={{color:'var(--text-tertiary)'}}>Keep your preference private on this device.</p></div><Toggle value={privateAnalysis} label="Toggle private analysis" onChange={toggle}/></div><div className="pt-5"><p className="text-xs uppercase tracking-[.12em]" style={{color:'var(--text-tertiary)'}}>Active protection services</p><div className="mt-3 grid sm:grid-cols-2 gap-2">{Object.entries(health?.agents||{}).map(([agent,mode])=><div key={agent} className="rounded-xl p-3" style={{background:'var(--bg-tertiary)',border:'1px solid var(--border)'}}><span className="text-sm capitalize">{agent.replace('_',' ')}</span><span className="block mt-1 text-xs" style={{color:mode==='real'?'var(--safe)':'var(--text-tertiary)'}}>{mode}</span></div>)}</div></div></Card></Shell>;
}

export function CheckHistory() {
  const [checks,setChecks]=useState([]);const [busy,setBusy]=useState(false);const {addToast}=useApp(); const navigate=useNavigate();
  const load=()=>fetch('/api/checks',{credentials:'include'}).then(r=>r.ok?r.json():[]).then(setChecks);useEffect(load,[]);
  const clear=async()=>{if(!window.confirm('Clear all saved checks and chat history? This cannot be undone.'))return;setBusy(true);const r=await fetch('/api/profile/history',{method:'DELETE',credentials:'include'});setBusy(false);if(!r.ok)return addToast({type:'error',message:'Could not clear history.'});setChecks([]);addToast({type:'success',message:'Saved check and chat history cleared.'});};
  return <Shell eyebrow="Support & privacy" title="Check history"><div className="flex justify-between items-center mb-4"><p className="text-sm" style={{color:'var(--text-secondary)'}}>{checks.length} saved check{checks.length===1?'':'s'}</p>{checks.length>0&&<Button variant="danger" size="sm" loading={busy} onClick={clear}><Trash2 size={15}/> Clear history</Button>}</div>{checks.length?<div className="space-y-3">{checks.map(check=>{const danger=check.level==='danger';return <Card key={check.id} padding={false} onClick={()=>navigate(`/trace/${check.id}`)}><div className="p-4 flex items-center gap-3"><span className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background:danger?'var(--threat-dim)':'var(--accent-dim)',color:danger?'var(--threat)':'var(--accent)'}}>{danger?<ShieldAlert size={19}/>:<CheckCircle2 size={19}/>}</span><div className="flex-1"><p className="font-semibold capitalize">{check.kind} check</p><p className="text-xs mt-1" style={{color:'var(--text-tertiary)'}}>{new Date(check.created_at*1000).toLocaleString()} · {check.level||'processing'}</p></div><span className="text-sm font-semibold" style={{color:danger?'var(--threat)':'var(--safe)'}}>{check.risk!=null?`${Math.round(check.risk*100)}%`:'—'}</span></div></Card>})}</div>:<Card hover={false}><History size={28} style={{color:'var(--accent)'}}/><p className="mt-3 font-semibold">No saved checks yet</p><p className="mt-1 text-sm" style={{color:'var(--text-secondary)'}}>Run a Scam Check to build your personal safety history.</p><Button className="mt-4" onClick={()=>navigate('/scam-check')}>Start a check</Button></Card>}</Shell>;
}

export function HelpCentre() {
  const navigate=useNavigate();
  const banks=[['Affin Bank','03-8230 2222'],['Agrobank','1300-88-2476'],['Alliance Bank','03-5516 9800'],['AmBank','03-2178 8888'],['Bank Islam','03-2690 0900'],['Bank Muamalat','03-2615 8000'],['Bank Rakyat','1300-80-5454'],['BSN','1300-88-1900'],['CIMB','03-6204 7788'],['Hong Leong Bank','03-7626 8899'],['HSBC','1300-88-1388'],['Maybank','03-5891 4744'],['Public Bank','03-2177 3555'],['RHB','03-9206 8118'],['UOB','03-2612 8100']];
  return <Shell eyebrow="Support & privacy" title="Help centre"><div className="grid gap-3">
    <Card hover={false}><CircleHelp style={{color:'var(--accent)'}}/><h2 className="mt-3 font-semibold">If you think you are being scammed</h2><ol className="mt-3 space-y-2 text-sm list-decimal pl-5" style={{color:'var(--text-secondary)'}}><li>Stop replying and do not transfer money or share TAC/OTP codes.</li><li>Save the chat, transaction receipt, phone number, and link as evidence.</li><li>Call your bank through an official number—not one sent by the caller.</li><li>If a transfer has happened, call NSRC at <a href="tel:997" style={{color:'var(--accent)'}}>997</a> as soon as possible.</li></ol></Card>
    <Card hover={false}><ShieldAlert style={{color:'var(--threat)'}}/><h2 className="mt-3 font-semibold">Urgent support</h2><p className="mt-1 text-sm" style={{color:'var(--text-secondary)'}}>NSRC helps coordinate urgent scam reports. Police emergencies should go to 999. These calls open your phone dialler.</p><div className="flex gap-2 mt-4"><a href="tel:997" className="rounded-xl px-4 py-3 text-sm font-semibold no-underline" style={{background:'var(--threat-dim)',color:'var(--threat)',border:'1px solid var(--threat)'}}>Call NSRC 997</a><a href="tel:999" className="rounded-xl px-4 py-3 text-sm font-semibold no-underline" style={{background:'var(--warning-dim)',color:'var(--warning)',border:'1px solid var(--warning)'}}>Call 999</a></div></Card>
    <Card hover={false}><h2 className="font-semibold">Bank scam hotlines</h2><p className="mt-1 text-sm" style={{color:'var(--text-secondary)'}}>Common Malaysia bank contacts. Confirm the latest number on your bank’s official website before calling.</p><div className="grid sm:grid-cols-2 gap-2 mt-4">{banks.map(([name,number])=><a key={name} href={`tel:${number.replace(/[^+\\d]/g,'')}`} className="flex justify-between gap-3 rounded-lg px-3 py-3 text-sm no-underline" style={{background:'var(--bg-tertiary)',border:'1px solid var(--border)',color:'var(--text-primary)'}}><span>{name}</span><strong style={{color:'var(--accent)',whiteSpace:'nowrap'}}>{number}</strong></a>)}</div></Card>
    <Card hover={false}><MessageCircle style={{color:'var(--accent)'}}/><h2 className="mt-3 font-semibold">Ask DJAGA Assistant</h2><p className="mt-1 text-sm" style={{color:'var(--text-secondary)'}}>Ask about a suspicious message, call, link, bank account, or payment request. DJAGA can search your saved checks and the app’s live intelligence.</p><Button className="mt-4" onClick={()=>navigate('/chat')}>Open assistant</Button></Card>
  </div></Shell>;
}
